#!/usr/bin/env lua

package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

local sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar. This improves startup times drastically.
sbar.begin_config()
require("init")
-- Enables hotloading of sketchybar config. ONLY ENABLE DURING DEVELOPMENT!!!
-- sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
