#!/usr/bin/env zsh
# shellcheck shell=bash

# Contains aliases for interactive zsh shells.

# Core replacements
alias cat=bat
alias df=duf
alias du=dust
alias find=fd
alias grep=rg
alias ls=eza

# Claude
alias claudex="claude --dangerously-skip-permissions --worktree"

# Editor
alias edit="\$EDITOR"

# zsh
alias ..="cd .."
alias back="popd"
alias recomp="compinit -d \$ZSH_COMPDUMP"
alias reload="source \$ZSH_CONFIG_HOME/.zshrc"
# Dotfiles
alias edit-aliases="edit \$DOTFILES/dot_config/zsh/dot_zshrc_aliases"
alias edit-dot="code \$DOTFILES/dotfiles.code-workspace"
alias edit-skhd="edit \$DOTFILES/dot_config/skhd/skhdrc"
# homebrew
alias brewload="brew update && brew upgrade && brew cleanup"
# ls
alias lsa="ls -al"
# nvim
alias vi=nvim
alias vim=nvim

# git
# Browse worktrees interactively in tig
function twig() {
  local worktree
  worktree=$(git worktree list --porcelain | awk '/^worktree/ {print $2}' | fzf)
  [[ -n "$worktree" ]] && tig -C "$worktree"
}
