#!/usr/bin/env zsh
# shellcheck shell=bash

# Set title to blank space before each prompt/command (Override Ghostty's default title icon)
_title_precmd() { print -n "\e]2; \a"; }
_title_preexec() { print -n "\e]2; \a"; }
add-zsh-hook precmd _title_precmd
add-zsh-hook preexec _title_preexec
