#!/usr/bin/env zsh
# shellcheck shell=bash
# shellcheck disable=SC2296

# Contains my zsh environment variables for interactive zsh shells.

# XDG Base Directory
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_RUNTIME_DIR="/var/folders/b6/4_zp7n2n6p79mqbmg5fj97t40000gn/T/"
export XDG_DATA_DIRS="/usr/share:/usr/local/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# zsh
export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
export ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump"

# Dotfiles
export DOTFILES="${XDG_DATA_HOME}/chezmoi"

# Editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# eval-cache
# Included convenience function _evalcache_clear clears eval-cache/
export ZSH_EVALCACHE_DIR="${XDG_CACHE_HOME}/eval-cache"
# export ZSH_EVALCACHE_DISABLE=true   # Bypass evalcache

# Homebrew
export HOMEBREW_PREFIX="/opt/homebrew"
homebrew_opt_prefix="${HOMEBREW_PREFIX}/opt"
export PATH="${HOMEBREW_PREFIX}/bin:${PATH}"

# gpg
export GPG_TTY="$TTY"

# gnu-getopt
export PATH="${homebrew_opt_prefix}/gnu-getopt/bin:${PATH}"

# goenv
export GOENV_ROOT="${homebrew_opt_prefix}/goenv"
export PATH="${GOENV_ROOT}/bin:${PATH}"

# grep
export PATH="${homebrew_opt_prefix}/grep/libexec/gnubin:${PATH}"

# nvim
export VIM="${XDG_CONFIG_HOME}/nvim"
export VIMRUNTIME="${homebrew_opt_prefix}/neovim/share/nvim/runtime/"

# Postgres
export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c@78/lib/pkgconfig:$PKG_CONFIG_PATH"

# sqlite
export CPPFLAGS="-I${homebrew_opt_prefix}/sqlite/include"
export LDFLAGS="-L${homebrew_opt_prefix}/sqlite/lib"
export PATH="${homebrew_opt_prefix}/sqlite/bin:${PATH}"
export PKG_CONFIG_PATH="${homebrew_opt_prefix}/zlib/lib/pkgconfig"

# uv
export PATH="$HOME/.local/share/../bin:$PATH"

# zlib
export CPPFLAGS="-I${homebrew_opt_prefix}/zlib/include"
export LDFLAGS="-L${homebrew_opt_prefix}/zlib/lib"
export PKG_CONFIG_PATH="${homebrew_opt_prefix}/zlib/lib/pkgconfig"

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=128

# agkozak/zsh-z
export _Z_DATA="$XDG_CACHE_HOME/z/.z"

# Release local variables
unset homebrew_opt_prefix
