#!/usr/bin/env zsh
# shellcheck shell=bash disable=SC1009,SC1072,SC1073,SC1083,SC2296

# Contains my zsh configuration for interactive zsh shells.

######## Benchmark Tools #######
# zmodload profiles zsh startup calls and start_time/end_time are used to
# calculate execution time. These tools should be used separately for accurate
# results. Make sure to uncomment the corresponding commands at the bottom of
# this script as well.
#
# zmodload zsh/zprof
zmodload zsh/datetime
_zsh_start_time=$EPOCHREALTIME
####### Benchmark Tools #######

autoload -Uz add-zsh-hook compinit

# Environment variables
source "$HOME/.config/zsh/.zshrc_env"

# Enable Powerlevel10k instant prompt. Should stay close to the top of
# ~/.config/zsh/.zshrc. Initialization code that may require console input
# (password prompts, [y/n] confirmations, etc.) must go above this block;
# everything else may go below.
if [[ -f "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	# shellcheck disable=SC1090
	source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Recompile config files if source is newer than bytecode.
() {
	local f
	for f in \
		"${HOME}/.config/zsh/.zshrc" \
		"${HOME}/.config/zsh/.zshrc_env" \
		"${HOME}/.config/zsh/.zshrc_aliases" \
		"${HOME}/.config/zsh/.zshrc_evals" \
		"${HOME}/.config/zsh/.zshrc_hooks" \
		"${HOME}/.config/zsh/.p10k.zsh"; do
		[[ -f "$f" && "${f}.zwc" -nt "$f" ]] || zcompile "$f" 2>/dev/null
	done
}

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
if [[ -f "$XDG_CONFIG_HOME/zsh/.p10k.zsh" ]]; then
	source "$XDG_CONFIG_HOME/zsh/.p10k.zsh"
fi

# Load antidote and plugins
source "$HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh"
zsh_config_home="${XDG_CONFIG_HOME}/zsh"
if [[ ! -f "$zsh_config_home/.zsh_plugins.zsh" || "$zsh_config_home/.zsh_plugins.txt" -nt "$zsh_config_home/.zsh_plugins.zsh" ]]; then
	antidote bundle < "$zsh_config_home/.zsh_plugins.txt" > "$zsh_config_home/.zsh_plugins.zsh"
fi
source "$zsh_config_home/.zsh_plugins.zsh"

# Lazy load evals, and completions
source "$zsh_config_home/.zshrc_evals"
zsh-defer compinit

# Load aliases and hooks
source "$zsh_config_home/.zshrc_aliases"
source "$zsh_config_home/.zshrc_hooks"

# Release local variables
unset zsh_config_home

####### Benchmark Tools #######
# zprof
printf 'Load Time: %.0f ms\n' "$(((EPOCHREALTIME - _zsh_start_time) * 1000))"
####### Benchmark Tools #######
