#!/usr/bin/env zsh
# shellcheck shell=bash disable=SC2034

# zsh options

# Directory
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS

# History
mkdir -p "$ZSH_STATE_HOME"
HISTFILE="$ZSH_STATE_HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY

# Misc
setopt INTERACTIVE_COMMENTS

# mroth/evalcache
# Included convenience function _evalcache_clear clears eval-cache/
ZSH_EVALCACHE_DIR="$XDG_CACHE_HOME/eval-cache"
# ZSH_EVALCACHE_DISABLE=true   # Bypass evalcache

# rupa/z
_Z_DATA="$XDG_CACHE_HOME/z/.z"

# zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=128
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
