#!/usr/bin/env zsh
# shellcheck shell=bash

# Contains my zsh environment variables for interactive zsh shells.

# zsh
export ZSH_CACHE_HOME="$XDG_CACHE_HOME/zsh"
export ZSH_COMPDUMP="$ZSH_CACHE_HOME/.zcompdump"
export ZSH_CONFIG_HOME="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPLETIONS_HOME="$ZSH_CONFIG_HOME/completions"
export ZSH_DATA_HOME="$XDG_DATA_HOME/zsh"
