#!/usr/bin/env zsh
# shellcheck shell=bash disable=SC1009,SC1072,SC1073,SC1083,SC2296

# Contains my zsh configuration for interactive zsh shells.

######## Benchmark Tools #######
# zmodload profiles zsh startup calls and start_time/end_time are used to
# calculate execution time. These tools should be used separately for accurate
# results. Make sure to uncomment the corresponding commands at the bottom of
# this script as well.
#
# zmodload zsh/zprof
zmodload zsh/datetime
_zsh_start_time=$EPOCHREALTIME
####### Benchmark Tools #######

autoload -Uz add-zsh-hook compinit

# Recompile config files if source is newer than bytecode.
() {
	local f
	for f in \
		"$HOME/.config/zsh/.zshrc" \
		"$HOME/.config/zsh/.zshrc_env" \
		"$HOME/.config/zsh/.zshrc_evals" \
		"$HOME/.config/zsh/.zshrc_aliases" \
		"$HOME/.config/zsh/.zshrc_hooks" \
		"$HOME/.config/zsh/.zshrc_bindings" \
		"$HOME/.config/zsh/.zshrc_opts" \
		"$HOME/.config/zsh/.p10k.zsh"; do
		[[ -f "$f" && "${f}.zwc" -nt "$f" ]] || zcompile "$f" 2>/dev/null
	done
}

# Environment variables
source "$HOME/.config/zsh/.zshrc_env"

# Enable Powerlevel10k instant prompt. Should stay close to the top of
# ~/.config/zsh/.zshrc. Initialization code that may require console input
# (password prompts, [y/n] confirmations, etc.) must go above this block;
# everything else may go below.
if [[ -f "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	# shellcheck disable=SC1090
	source "$XDG_CACHE_HOME/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
if [[ -f "$XDG_CONFIG_HOME/zsh/.p10k.zsh" ]]; then
	source "$XDG_CONFIG_HOME/zsh/.p10k.zsh"
fi

# Load antidote and plugins
source "$HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh"
if [[ ! -f "$ZSH_CONFIG_HOME/.zsh_plugins.zsh" || "$ZSH_CONFIG_HOME/.zsh_plugins.txt" -nt "$ZSH_CONFIG_HOME/.zsh_plugins.zsh" ]]; then
	antidote bundle <"$ZSH_CONFIG_HOME/.zsh_plugins.txt" >"$ZSH_CONFIG_HOME/.zsh_plugins.zsh"
fi
source "$ZSH_CONFIG_HOME/.zsh_plugins.zsh"

# Lazy load evals
source "$ZSH_CONFIG_HOME/.zshrc_evals"

# Load aliases, bindings, hooks, and options
source "$ZSH_CONFIG_HOME/.zshrc_aliases"
source "$ZSH_CONFIG_HOME/.zshrc_bindings"
source "$ZSH_CONFIG_HOME/.zshrc_hooks"
source "$ZSH_CONFIG_HOME/.zshrc_opts"

# Recache completions if older than 24 hours
local compdump_is_stale=($ZSH_COMPDUMP(Nmh+24))
if (($#compdump_is_stale)); then
	compinit -d $ZSH_COMPDUMP
else
	compinit -C -d $ZSH_COMPDUMP
fi

####### Benchmark Tools #######
# zprof
printf 'Load Time: %.0f ms\n' "$(((EPOCHREALTIME - _zsh_start_time) * 1000))"
####### Benchmark Tools #######
