name: Format, Lint

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@v4.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install node dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@v4.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python dependencies
        run: uv sync --dev

      - name: Lint
        run: pnpm run lint
